deployment:
  tasks:
    - export DEPLOYPATH=/home/u1525344/kua
    - export PUBLICPATH=/home/u1525344/public_html/bantu-kua
    
    # 1. Copy Core Files to Private Directory
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH
    
    # 2. Copy Public Assets to Public Directory
    - /bin/cp -R public/assets $PUBLICPATH
    - /bin/cp -R public/template $PUBLICPATH
    - /bin/cp public/favicon.ico $PUBLICPATH
    - /bin/cp public/robots.txt $PUBLICPATH
    - /bin/cp public/.htaccess $PUBLICPATH
    - /bin/cp public/sw-display.js $PUBLICPATH


  

  
